apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-rs
spec:
  template:
    metadata:
      name: my-pod
      labels:
        app: my-app
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 1
  selector: 
    matchLabels:
      app: my-app