apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-express-deployment
  labels:
    app: hello-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-express
  template:
    metadata:
      labels:
        app: hello-express
    spec:
      containers:
      - name: hello-express
        image: hello-express:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-express-service
spec:
  type: NodePort
  selector:
    app: hello-express
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30101